### ENDPOINTS RECIPES

### CREATE RECIPE
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVkZjQ2MDBkLWMxYjItNGQ3NC1hZGEyLWU0ZWFhYjU0NzI4YiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjM1MTUwNjgsImV4cCI6MTY2MzYwMTQ2OH0.XB06mKpUmn6pBI7h6YG_UyCk1SquJX2uGDxPUtmzOXA
# @name create

POST http://localhost:3003/recipes/create
Authorization: {{token}}
Content-Type: application/json

{
    "title": "Farofa",
    "description": "Escolhendo a mistura certa você faz uma boa fafora.",
    "prepare": "Misture a farofa com o qeu você quiser."
}

### GET ALL RECIPES
GET http://localhost:3003/recipes/feed
Content-Type: application/json

### GET RECIPE BY ID
GET http://localhost:3003/recipes/bae4a797-5e0e-42f3-b451-8c8c3e5fd313
Authorization: {{token}}
Content-Type: application/json
