### 1) Signup
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Ralph",
    "email": "ralph@email.com",
    "password": "123456"
  
}

### 2) Login
# @name login

POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "astrodev@gmail.com",
    "password": "bananinha"
}

### 3) Get All
@token = {{login.response.body.token}}
GET http://localhost:3003/users
Content-Type: application/json

### 4) Delete User
DELETE http://localhost:3003/users/7079b8e4-95cd-48aa-82a9-77454e94b789
Authorization: {{token}}

