### 1) Signup
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Jake",
    "email": "jake@email.com",
    "password": "123456"
}

### 2) Login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "jake@email.com",
    "password": "123456"
}

### 3) Get All
GET http://localhost:3003/users
Content-Type: application/json