# @name signup

POST http://localhost:3003/user/signup
Content-Type: application/json

{
   "name": "Admin", 
   "nickname": "adm", 
   "email": "admin@email.com" ,
   "password": "3306@3306",
   "role": "ADMIN"
}
###
# @name login

POST http://localhost:3003/user/login
Content-Type: application/json

{
   "email": "admin@email.com" ,
   "password": "3306@3306"
}


###

@token = {{login.response.body.token}}

PUT http://localhost:3003/user/edit
Authorization: {{token}}
Content-Type: application/json

{
   "name": "NOME" 
}

###
GET http://localhost:3003/user/profile
Authorization: {{token}}

###

DELETE http://localhost:3003/user/a47da31c-e956-4931-8538-57c918b6ae81
Authorization: {{token}}

ALTER TABLE to_do_list_users ADD ENUM ("NORMAIL", "ADMIN") NOT NULL DEFAULT "NORMAL";

###
GET http://localhost:3003/user
Authorization: {{token}}
